CREATE DATABASE PROVA01;
GO
USE PROVA01;

CREATE TABLE USERS
(
	USERID INT CONSTRAINT PK_USERID PRIMARY KEY IDENTITY(1,1),
	LOGIN VARCHAR(30) CONSTRAINT NN_LOGIN NOT NULL,
	PASSWORD VARCHAR(30) CONSTRAINT NN_PASSWORD NOT NULL
);

CREATE TABLE PEOPLE
(
	PEOPLEID INT CONSTRAINT PK_PEOPLEID PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(100) CONSTRAINT NN_NAME NOT NULL,
	PASSPORT VARCHAR(50) CONSTRAINT NN_PASSPORT NOT NULL,
	USERID INT CONSTRAINT FK_USERID FOREIGN KEY REFERENCES USERS(USERID) NOT NULL
);

INSERT INTO USERS VALUES('opaa','teste')